["Scene Parameters"]
num_buildings_min = 10
num_buildings_max = 20
min_size = 0.5
max_size = 4.0
min_height = 1.0
max_height = 8.0
area_size = 8.0
exclusion_radius = 2.0

[Frequency]
frequency = 3500000000